### ISSUE TITLE
I can't find anything from the link you sent 

### ISSUE THREAD

**Issue by wangzheliu** [chahuja/pats#2]
I received your email and opened the email URL, but it showed that "we could not find the page you were looking for."

**Comment by chahuja** [comment]
That's weird. Could you reply to the email that was sent to you so I can verify the link?

**Comment by wangzheliu** [comment]
> 
> 
> That's weird. Could you reply to the email that was sent to you so I can verify the link?

1407aichiji@gmail.com        thank you!
