### ISSUE TITLE
How to access frames?

### ISSUE THREAD

**Issue by stavshem** [chahuja/pats#4]
Hi,

How do I access the original frames (images, not pose) by index?

For example, how can I obtain the relevant frames for the word `you` (frames 7-9)?

```
pd.read_hdf('pats/data/processed/bee/cmu0000025735.h5', key='text/meta')
```
  | Word | start_frame | end_frame
-- | -- | -- | --
0 | do | 0.0 | 7.0
1 | you | 7.0 | 9.0
2 |have | 9.0 | 10.0

Thank you

**Comment by chahuja** [comment]
We do not provide the image frames of the original video for 2 reasons: (1) Copyright issues and (2) image frames would increase the size of the dataset considerably. If you need the image frames, you would have to download the youtube videos (for which we provide a tool) and then use `ffmpeg` or any other such library to extract the frames.
